apiVersion: apps/v1
kind: Deployment
metadata:
  name: kube-node-ready-controller
  namespace: kube-system
  labels:
    application: kube-node-ready-controller
    version: latest
spec:
  strategy:
    type: Recreate
  selector:
    matchLabels:
      application: kube-node-ready-controller
  template:
    metadata:
      labels:
        application: kube-node-ready-controller
        version: latest
    spec:
      tolerations:
      - key: node.alpha.kubernetes.io/notReady-workload
        operator: Exists
        effect: NoSchedule
      containers:
      - name: kube-node-ready-controller
        image: mikkeloscar/kube-node-ready-controller:latest
        args:
        # format <namespace>:<labelKey>=<labelValue>,+
        - "--pod-selector=kube-system:application=skipper-ingress"
        - "--pod-selector=kube-system:application=kube2iam"
        - "--pod-selector=kube-system:application=kube-proxy"
        - "--pod-selector=kube-system:application=logging-agent"
        - "--pod-selector=kube-system:application=prometheus-node-exporter"
        resources:
          limits:
            cpu: 20m
            memory: 50Mi
          requests:
            cpu: 20m
            memory: 50Mi
